### ISSUE TITLE
Error log on passage proofreader

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#178]
https://drive.google.com/open?id=0B-r431ws0zjXN1RSUVhRWkNGa0E

**Comment by wlaurance** [comment]
```
Download the React DevTools for a better development experience: http://fb.me/react-devtools
Uncaught SyntaxError: Unexpected token i
Error: Could not find concept corresponding to rule number: 101
    at https://quillgrammarstaging.firebaseapp.com/app-c7bb2980.js:11590:19
    at Function._.map._.collect (https://quillgrammarstaging.firebaseapp.com/vendors.min.js:33273:24)
    at _.(anonymous function) [as map] (https://quillgrammarstaging.firebaseapp.com/vendors.min.js:34597:34)
    at getLocalResults (https://quillgrammarstaging.firebaseapp.com/app-c7bb2980.js:11583:10)
    at ProofreadingPassage.saveLocalResults (https://quillgrammarstaging.firebaseapp.com/app-c7bb2980.js:11608:17)
    at showResults (https://quillgrammarstaging.firebaseapp.com/app-c7bb2980.js:9272:25)
    at Object.$scope.modal.buttonClick (https://quillgrammarstaging.firebaseapp.com/app-c7bb2980.js:9296:9)
    at fn (eval at <anonymous> (https://quillgrammarstaging.firebaseapp.com/vendors.min.js:13231:15), <anonymous>:4:270)
    at callback (https://quillgrammarstaging.firebaseapp.com/vendors.min.js:23411:17)
    at Scope.$eval (https://quillgrammarstaging.firebaseapp.com/vendors.min.js:15916:28)
TypeError: Cannot read property 'length' of null
    at calculatePercentage (calculatePercentage.js:30)
    at finalize.js:39
    at processQueue (vendors.min.js:14634)
    at vendors.min.js:14650
    at Scope.$eval (vendors.min.js:15916)
    at Scope.$digest (vendors.min.js:15727)
    at Scope.$apply (vendors.min.js:16024)
    at HTMLButtonElement.<anonymous> (vendors.min.js:23416)
    at HTMLButtonElement.eventHandler (vendors.min.js:3293)
    at HTMLButtonElement.nrWrapper (pf?student=QF53VoukQ1DTSUOqaVYltg&uid=E0COBlHa6wFi0fiSdmN8bg:6)
An error occurred while saving results to the LMS TypeError: Cannot read property 'length' of null(…)
TypeError: Cannot read property 'length' of null
    at calculatePercentage (calculatePercentage.js:30)
    at finalize.js:39
    at processQueue (vendors.min.js:14634)
    at vendors.min.js:14650
    at Scope.$eval (vendors.min.js:15916)
    at Scope.$digest (vendors.min.js:15727)
    at Scope.$apply (vendors.min.js:16024)
    at HTMLButtonElement.<anonymous> (vendors.min.js:23416)
    at HTMLButtonElement.eventHandler (vendors.min.js:3293)
    at HTMLButtonElement.nrWrapper (pf?student=QF53VoukQ1DTSUOqaVYltg&uid=E0COBlHa6wFi0fiSdmN8bg:6)
```

**Comment by wlaurance** [comment]
Issue with "couldn't find associated concept"
![screen shot 2015-10-16 at 3 44 35 pm](https://cloud.githubusercontent.com/assets/1059214/10554923/f2d704aa-741c-11e5-8dbc-8238e706a74d.png)

The first two arrays (same array) represent a unique list of rule numbers the passage has.

The next step loads those concepts (found by rule number). As you can see in the proofreader object, the concepts array only has length 2. It is missing 2 of the 4 concepts it should have loaded.

![screen shot 2015-10-16 at 3 46 56 pm](https://cloud.githubusercontent.com/assets/1059214/10554945/28fe02b8-741d-11e5-974c-d0bd8f18da5d.png)

Above is the code that finds the rule numbers out of the master list `firebase/v2/concepts` by rule number.
