### ISSUE TITLE
Optipng executable not found

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#45]
I was not able to create a build of the app on my local machine, as I was getting the following error when running `gulp --envs=prod` : 

```
[13:33:23] Using gulpfile ~/Quill-Grammar/gulpfile.js
[13:33:23] Starting 'default'...
[13:33:23] Starting 'clean'...
[13:33:23] Finished 'default' after 7.7 ms
[13:33:23] Finished 'clean' after 24 ms
[13:33:23] Starting 'assets'...
[13:33:23] Starting 'config'...
[13:33:23] Starting 'lint'...
[13:33:23] Starting 'styles'...
[13:33:23] Starting 'templates'...

events.js:85
     throw er; // Unhandled 'error' event
           ^
Error: spawn /Users/marcellomarcellosachs/code/Quill-Grammar/node_modules/empirical-angular-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT
   at exports._errnoException (util.js:746:11)
   at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
   at child_process.js:1144:20
   at process._tickCallback (node.js:355:11) 
```

**Comment by marcellosachs** [comment]
@wlaurance  pointed out that it was due to the system not being able to locate an executable for optipng.
I then noticed that the app directory has two folders for optipng, one which has as a descendant file an executable, and one which doesn't. Essentially, the system was looking in the folder which didn't have the executable. Thus, I was able to fix this error by creating a copy of the executable and putting it in the folder in which it was absent.

* The folder which did not have the executable (but is where the system looks for it) : *
**FILEPATH1**
Quill-Grammar/node_modules/empirical-angular-gulp-tasks/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor

** Note : vendor was not even present as a subfolder of optipng-bin above, so I had to create it **

* The folder which does contain the executable file: *
** FILEPATH2 **
Quill-Grammar/node_modules/optipng/node_modules/optipng-bin/vendor/osx/

And so my solution involved 
1) copying a file titled 'optipng' that was located in the osx folder above in ** FILEPATH2 **
2) creating a subfolder 'vendor' of the optipng-bin folder in ** FILEPATH1 **
3) putting the copy of optipng in the new vendor subfolder mentioned in 2).
